# Generated by Django 3.2 on 2023-02-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230226_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=2, max_length=254, unique=True, verbose_name='Электронный адрес почты'),
            preserve_default=False,
        ),
    ]
